GET http://localhost:8080/

###
GET http://localhost:8080/keys

###
GET http://localhost:8080/value?key=alpha%2Fbeta

###

GET http://localhost:8080/value?key=alpha%2Ffuck

###

POST http://localhost:8080/value?key=alpha%2Ffuck&value=no